### ISSUE TITLE
Locale warning on Linux

### ISSUE THREAD

**Issue by igiagkiozis** [plotly/Kaleido#10]
Hi @jonmmease, 

I get the following warning on linux:
[0710/121110.792499:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale 
Plot seems to generated just fine. Any ideas? 

Regards,
Ioannis

**Comment by jonmmease** [comment]
Hi @igiagkiozis,

I've seen that too, and I haven't tracked down the cause.  In general, chromium writes several kinds of warning messages to standard-err that don't seem to cause any issues so I'd recommend capturing standard error of the subprocess so it's doesn't make its way to users.

What I do in the Python library is use a background thread to continually read standard error into a buffer. Then I only display it to the user if Kaleido initialization crashes (e.g. doesn't even return an error message on standard out), or if an image export request returns nothing on standard output (I've only seen this happen when passing a 200MB+ JSON bundle, when Chromium raises an internal error that the max message buffer size is exceeded).

**Comment by igiagkiozis** [comment]
Hi @jonmmease, 

Yes, that did the trick, thanks!
