### ISSUE TITLE
Loading message for MathJax is included in the output PDF file

### ISSUE THREAD

**Issue by s417-lama** [plotly/Kaleido#101]
Environments:

- Ubuntu 18.04
- Python 3.6.9
- Plotly.py 5.1.0
- Kaleido 0.2.1

Issue:

```py
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Bar(
    x=[1, 2, 3, 4],
    y=[20, 9, 25, 16],
))
fig.write_image("test.pdf")
```
generates the following PDF file, which includes an unnecessary loading message for MathJax.

[test.pdf](https://github.com/plotly/Kaleido/files/6900819/test.pdf)

**Comment by Miosss** [comment]
+1
I have the same issue on Windows 10.

**Comment by bgottschall** [comment]
If you do not need MathJAX a temporary workaround is disabling it:
`import plotly.io as pio
pio.kaleido.scope.mathjax = None`

**Comment by nicolaskruchten** [comment]
Duplicated by #122 and we will follow up there.

**Comment by marc-git** [comment]
I'm getting this error now too. Should I open a new issue?
