### ISSUE TITLE
Installing on Raspberry Pi Zero 

### ISSUE THREAD

**Issue by DVehlow** [plotly/Kaleido#105]
I am trying to install kaleido on my Raspberry Pi Zero W. 

I keep getting the error:

ERROR: Could not find a version that satisfies the requirement kaleido (from versions: none)

I have tried using pip, pip3 and updated the version of pip to 21.2.4. I have also tried specifying the version of kaleido from the list in PyPI

I have followed all the current issues on installation but cannot seem to get this working at all. 

Bellow is an image of some details I have seen asked for in previous issue threads. 

![image](https://user-images.githubusercontent.com/24698616/129382438-354fbce3-6f64-47f4-b949-6e39f19f28c8.png)

**Comment by jonmmease** [comment]
Hi @DVehlow,
The reason you're not able to install kaleido is that we don't have a build for the armv6l architecture at this point.  We do have armv7l, and it might be possible to create an armv6l build as well. It would take a little research to see if chromium currently supports that architecture.

**Comment by martennilsson** [comment]
hi, any development on this?

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
