### ISSUE TITLE
pip install missing kaleido.cmd file

### ISSUE THREAD

**Issue by Carolzheng** [plotly/Kaleido#111]
I'm on Windows and installed using pip wheel kaleido-0.2.1.post1-py2.py3-none-manylinux2014_armv7l.whl. (this does not seem the right one to use but seems to be the only pip package available. 
After installation, in path "...\anaconda3\Lib\site-packages\kaleido\executable", I only have file kaleido but no kaleido.cmd, leading to error when executing in python. 

ValueError: 
The kaleido executable is required by the kaleido Python library, but it was not included
in the Python package and it could not be found on the system PATH.
Searched for included kaleido executable at:
    ...\anaconda3\Lib\site-packages\kaleido\executable\kaleido.cmd 
Searched for executable 'kaleido' on the following system PATH:
......

**Comment by jonmmease** [comment]
Hi @Carolzheng. Yeah, this wheel file won't work on Windows.  Can you add more detail on what version of Windows you're using, and how you tried to install kaleido?

**Comment by Carolzheng** [comment]
I'm on Windows 10, I tried to install by downloading this wheel file and then use pip install the wheel file - it actually didn't give me any error on the installation.

**Comment by jonmmease** [comment]
The recommend was to install kaleido is from PyPI (or conda-forge) so that the correct version for your operating system will be installed:
```
$ pip install kaleido
```
Have you tried this?  If so, did you get an error?

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
