### ISSUE TITLE
kaleido is taking too much space. Reduce module size

### ISSUE THREAD

**Issue by ievgennaida** [plotly/Kaleido#113]
For me kaleido is taking a lot of space
Example:

kaleido - 221MB
plotly - 140MB
scipy - 68MB
pandas - 57MB
pydantic - 45MB

Size has to be reduced, taking too much for some reason.

**Comment by jonmmease** [comment]
Hi @ievgennaida, kaleido is as large as it is because is compiles a headless version of the Chromium browser as a library.

There isn't currently anything we know of that can be done to reduce the size, but we would welcome suggestions.

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson

**Comment by millerick** [comment]
@gvwilson , where will that update be posted?
