### ISSUE TITLE
Why is there a name mismatch between the PyPI and Anaconda versions?

### ISSUE THREAD

**Issue by sgbaird** [plotly/Kaleido#117]
i.e.
PyPI: `kaleido`
Anaconda: `python-kaleido`

**Comment by gregorywaynepower** [comment]
How do I make sure that that conda users can get access to this without installing pip?

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
