### ISSUE TITLE
Installation of Kaleido using poetry macOS Monterey (M1)

### ISSUE THREAD

**Issue by jpetot** [plotly/Kaleido#125]
Installation of kaleido isn't working using poetry, but working with pip.

>` poetry add kaleido`
```
Using version ^0.2.1 for kaleido

Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing kaleido (0.2.1.post1): Failed

  RuntimeError

  Unable to find installation candidates for kaleido (0.2.1.post1)

  at ~/.poetry/lib/poetry/installation/chooser.py:72 in choose_for
       68│
       69│             links.append(link)
       70│
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│
       76│         # Get the best link
```

And with `pip`:
> `pip install kaleido`
```
Collecting kaleido
  Using cached kaleido-0.2.1-py2.py3-none-macosx_11_0_arm64.whl (85.8 MB)
Installing collected packages: kaleido
Successfully installed kaleido-0.2.1
Failed to add packages, reverting the pyproject.toml file to its original content.
```

I am using:
- macOS Monterey (M1)
- Poetry version 1.1.12

Related thread : #70

**Comment by kpostekk** [comment]
I have the same issue on Intel based Mac. Solution with pip helped me

**Comment by josteinbf** [comment]
Same issue here. By running `pip install kaleido` like suggested in previous comments, I noticed that pip is installing version `0.2.1`, which is different from `0.2.1.post1` that poetry tries to install. I then tried forcing poetry to use the same version as pip,
```sh
poetry add "kaleido@0.2.1"
```
which seems to work.

I don't know exactly what's going on here, but for me this is a useful workaround, at least.

**Comment by LunarLanding** [comment]
On M1 using conda installation fails due to mathjax 2.7.* not being available on osx-arm64 ( https://github.com/conda-forge/mathjax-feedstock/issues/16 )

**Comment by feliciov** [comment]
I'm having the same issue using poetry on Manjaro. Poetry goes for 0.2.1.post1 if not forced and fails.
Adding the 0.2.1v, as pointed by josteinbf, did worked too.

**Comment by jordankbartos** [comment]
I'm also experiencing this issue using poetry. My project depends on a project that depends on `kaleido>=0.2.1`. After running `poetry lock --no-update`, my `poetry.lock` file has kaleido pinned to version `0.2.1.post1`. Then installation fails because a version `0.2.1.post1` cannot be found in PyPI.

![image](https://user-images.githubusercontent.com/31391041/204665210-bec85541-3c71-4f7a-b96c-aa888f67c7d7.png)

![image](https://user-images.githubusercontent.com/31391041/204665076-5389662b-f1e9-45db-820a-e232dd75cc83.png)

**Comment by brunomcr** [comment]
install a previous version:

`poetry add kaleido==0.2.1 `

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
