### ISSUE TITLE
Using plotly in service file

### ISSUE THREAD

**Issue by reach-the-sky** [plotly/Kaleido#128]
While using python3 and running directly there is no problem but if we use service file, there is a problem with kaleido.

```Failed to start Kaleido subprocess. Error stream:
/home/ubuntu/pivony-api/env/lib/python3.7/site-packages/kaleido/executable/kaleido: line 2: dirname: command not found
/home/ubuntu/pivony-api/env/lib/python3.7/site-packages/kaleido/executable/kaleido: line 10: ./bin/kaleido: No such file or directory

**Comment by FridtjofKoene** [comment]
It has to do with the path.
In the python package of kaleido there exists a script named kaleido in:
......site-packages/kaleido/executable/

it has the following line in it:
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

the dirname program can't be found.
I changed for testing this line into:
DIR="$( cd "$( /usr/bin/dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

of course it would be better to update the PATH env but in my case it worked just fine.

if syslog mentions something about libnss3.so then try installing it with:
apt install libnss3

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
