### ISSUE TITLE
Code getting Stuck at .write_image wihout giving any error message

### ISSUE THREAD

**Issue by ramwarutkar** [plotly/Kaleido#133]
Hi,
I am running script on Python version 3.10.3 and Plotly version 5.2.1 and kaliedo version 0.2.1. The program is getting stuck at the point where the graphs are to be written. 

--- = px.bar(---, 
                   x="---", 
                      y="---", 
                      color="---",
                      hover_data=['---'], 
                      text = '---',
                      barmode = '---',
                      template = '---',
                      title='---',
                      opacity = 0.7,
                      color_discrete_sequence=["red", "blue", "green", "purple"])

---.write_image(---,width = 1000, height =600)

Kindly suggest a solution.

Thank you

**Comment by nordin59** [comment]
Same for me!!!

**Comment by ramwarutkar** [comment]
> Same for me!!!

**Comment by ramwarutkar** [comment]
Locate where the library are installed. Goto kaleido>executable> and create a folder named " kaleido " if not already and copy and paste kaleido.exe file form bin folder in it.

**Comment by ramwarutkar** [comment]
Goto where libraries are installed. Goto kaleido>executable and create a folder named " kaleido " and copy paste kaleido.exe from bin folder in it.

**Comment by ramwarutkar** [comment]
> Same for me!!!



> Same for me!!!

Locate where the library are installed. Goto kaleido>executable> and create a folder named " kaleido " if not already and copy and paste kaleido.exe file form bin folder in it.
