### ISSUE TITLE
Guidance: Support for Other Graphing Libraries

### ISSUE THREAD

**Issue by cgdeboer** [plotly/Kaleido#135]
I'm working on a production systems with some dependencies on non-Plotly JS based charting systems. After reading @jonmmease 's [post](https://medium.com/plotly/introducing-kaleido-b03c4b7b1d81) from a while ago, and seeing the success this project has had, I thought Kaleido might be a good alternative to our current approach (headless browser controlled by Phantom JS). 

I wanted to understand the long term goal of this project. If I were wanting to support something like chartist, D3, highcharts, amCharts, or morris.js, is the appropriate action to either:

1. Open an PR that adds additional [scopes](https://github.com/plotly/Kaleido/tree/master/repos/kaleido/py/kaleido/scopes) to the [main kaleido project](https://github.com/plotly/Kaleido/wiki/Scope-(Plugin)-Architecture).
2. Fork Kaleido and focus support another lib there under a different pypi name.
3. Some other path forward.

**Comment by jonmmease** [comment]
Hi @cgdeboer, I'm not with Plotly anymore and not using Kaleido actively.  That said, I do still think the project has a lot of promise for use cases like you mention.  I won't have bandwidth to do much development or maintenance myself, but I'd be happy to review PRs if you'd like to go that direction.

I'd also cc @alexcjohnson for the current Plotly perspective on the future of the project.

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
