### ISSUE TITLE
kaleido hangs when used multiple times or when saving large image

### ISSUE THREAD

**Issue by salmanrk** [plotly/Kaleido#139]
Hi
I'm using kaleido 0.2.1 with python 3.8.10. 
Im running a script that writes around 15 images. And it gets stuck somewhere. It used to work properly but for a couple of days its not. 
Also a while ago i made a script that writes 2 images. treemaps that are 6000x3000. It hanged after writing the first image. I tried shutting down kaleido after the first image so it starts fresh but that didnt work either. So I settled with just one image. 

Any solution?

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
