### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by cubocicloide** [plotly/Kaleido#140]
I am trying to install kaleido in a docker image. The dockerfile is as follows:

```
FROM python:3.9-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV CRYPTOGRAPHY_DONT_BUILD_RUST 1

RUN apk update \
    && apk add --virtual build-deps gcc make python3-dev musl-dev \
    && apk add --no-cache libffi-dev postgresql-client postgresql-contrib postgresql-dev bash git curl g++ libxslt-dev linux-headers coreutils \
    && apk add build-base libzmq zeromq-dev jpeg-dev zlib-dev libjpeg cairo-dev cairo cairo-tools pango-dev gdk-pixbuf-dev fontconfig gdal geos

RUN apk add --no-cache make
RUN apk add --update netcat-openbsd

ADD ./requirements.txt /tmp/

# Install PyPi dependencies
WORKDIR /tmp
RUN pip install --upgrade pip && pip install Cython==0.29.24 && pip install kaleido
RUN pip install uvicorn[standard]==0.14.0
RUN pip install -r requirements.txt

RUN apk del build-deps

ADD . /code/

RUN mkdir -p /storage/static
RUN mkdir -p /storage/media

RUN chmod -R a+rw /storage

ADD entrypoint.sh /
RUN chmod +x /entrypoint.sh

ADD worker-entrypoint.sh /
RUN chmod +x /worker-entrypoint.sh

WORKDIR /code/

EXPOSE 8000
EXPOSE 8001
```

However, when I run docker-compose up, the process exits with the following error:

```
ERROR: Could not find a version that satisfies the requirement kaleido (from versions: none)
ERROR: No matching distribution found for kaleido
```

NOTE: I am running docker on a Mac with Monterey OS

**Comment by kelleyrw** [comment]
I'm having the same error; however, I'm just trying to `pip install` from plan virtual env.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/4699694/176015888-6df58b66-d349-4b4a-b503-5f5bdaeff73d.png">

env:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/4699694/176016562-adb271cf-4705-4ec3-8552-3ee56e960771.png">

<img width="927" alt="image" src="https://user-images.githubusercontent.com/4699694/176016603-94bf4437-c770-407e-b774-bcd2f241fee2.png">

**Comment by cubocicloide** [comment]
I was able to get it working by changing the definition of my Dockerfile, which is now based on python:3.9 instead of python:3.9-alpine.

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson

**Comment by kgskgs** [comment]
so where are the news? still cannot install on alpine

**Comment by maribowman** [comment]
@gvwilson where news?

**Comment by ayjayt** [comment]
Hi, please refer to readme: https://github.com/plotly/Kaleido

On alpine, you must install chromium from their package manager.
