### ISSUE TITLE
installation from conda-forge failing on macos Montery (M1)

### ISSUE THREAD

**Issue by gksharer** [plotly/Kaleido#142]
I get an unsatisfiable error when I try to install python-kaleido from conda-forge on macos Montery (M1)

`conda install -c conda-forge python-kaleido`

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__osx==12.4=0
  - feature:|@/osx-arm64::__osx==12.4=0
  - python-kaleido -> kaleido-core=0.2.1 -> __osx[version='>=10.11']

Your installed version is: 12.4

**Comment by ThijsvZ** [comment]
I was having the same issue, identical output, but on Montery 12.5. Installation through pip did work.

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
