### ISSUE TITLE
Use a modern version of python

### ISSUE THREAD

**Issue by Pandapip1** [plotly/Kaleido#169]
The setup.py script seems to indicate that a python version of `<3.4` is required. This is horribly out of date, and means that I can't submit it as a package to [package managers that don't support python versions that old](https://github.com/spack/spack/pull/41190). Are there any plans to use a more modern python version?

**Comment by alexcjohnson** [comment]
@Pandapip1 are you referring to this line?

https://github.com/plotly/Kaleido/blob/3b590b563385567f257db8ff27adae1adf77821f/repos/kaleido/py/setup.py#L298

That's just saying "if python <3.4 we need to install pathlib." It doesn't say anything about which Python versions are supported by Kaleido, which is all of them AFAIK. Other Plotly projects currently use `>=3.6` so next time we make a Kaleido release it will probably move to that and this line can be removed entirely.
