### ISSUE TITLE
fig.write_image not working

### ISSUE THREAD

**Issue by urospetkovic** [plotly/Kaleido#189]
Hi there, i have an issue since last windows update - fig.write_image() stopped working. It just keeps 'running' in notebook or in streamlit while write_html() works just fine. I'm running Python 3.10.4 on Windows 10 pro, Dell Precision 3560. Here's the sample code:

import plotly.express as px
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
fig.show()
fig.write_html('123.html')
fig.write_image('123.png')

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
