### ISSUE TITLE
Static export fails for data with missing values

### ISSUE THREAD

**Issue by timmens** [plotly/Kaleido#228]
Hello!

I am having trouble writing static images with Plotly and Kaleido if data is missing after updating to Kaleido >= 0.4. I am wondering if I am doing something wrong.

---

### Versions

- python = 3.12.7
- numpy = 2.1.3
- plotly = 5.24.1
- kaleido = 0.4.1 (but also tested on 0.4.0)

### MRE

```python
import numpy as np
import plotly.express as px

# fig = px.scatter(x=[1, 2], y=[1, 2])  # this does not result in an error! (EDIT)
fig = px.scatter(x=[1, 2], y=[1, np.nan])

# works
fig.show()

# raises choreographer.browser.BrowserClosedError
fig.write_image("plotly.png")
```

### Notes

- The same code runs without error with Kaleido < 0.4.
- EDIT: The same code runs without error on Kaleido >= 0.4, when I replace `np.nan` with, say, 2.

---

Thank you!

**Comment by ayjayt** [comment]
Hi @timmens 

Thanks for posting this!

I don't think this has to do with data missing or not-

The new versions of Kaleido don't ship with a browser like they used to. They have to be installed separately- chrome or chromium.

If that's not the issue, please the env var `KALEIDO_DEBUG=true` before running the python (or in python with `os.environ['KALEIDO_DEBUG"]="true"`) and post the output here.

Happy to help!

Thanks

**Comment by ayjayt** [comment]
Thanks- that is so weird about the missing data, I will take a look at it.

**Comment by ayjayt** [comment]
Will be fixed by this PR into choreographer: https://github.com/plotly/choreographer/pull/167
