### ISSUE TITLE
Make available for general chart/html/report conversion to pdf

### ISSUE THREAD

**Issue by rubmz** [plotly/Kaleido#27]
Would be great to have this **outstanding** package for converting other types of charts/reports/htmls to pdf/svg/webp.

Worth noting that it works seamlessly under both windows 10 and linux! Did not believe it actually run chromium process under the hood. Amazing :-D

**Comment by jonmmease** [comment]
Hi @rubmz, 

> Worth noting that it works seamlessly under both windows 10 and linux! Did not believe it actually run chromium process under the hood. Amazing :-D

Thanks for letting us know. This is great to hear!

> Would be great to have this outstanding package for converting other types of charts/reports/htmls to pdf/svg/webp.

Yeah, there are definitely good use-cases here. I wrote up some notes on something similar in https://github.com/plotly/Kaleido/issues/21#issuecomment-664341383.  In this case, my assumption was that we would be working with an html document string, and a requested width/height, and would convert this into an image (PNG or JPG) or single page PDF of the requested dimensions. 

Could you take a look at this issue and see if this paradigm fits the use-cases you are interested in? And if not, could you write out a specific use case that would be useful for you?  Thanks!

Note that other image formats, like WEBP and SVG, wouldn't be so easy to support. For the plotly case, the plotly.js library knows how to generate these formats and the results are simply transferred from the JavaScript library back to the C++ executable.  Chromium has built-in capability to snapshot a webpage to PNG, JPG, and PDF without any cooperation from content being displayed.

**Comment by elijahsgh** [comment]
I just wanted to chime in with a bump for this feature. I got here looking for a "clean" way to convert basic HTML+CSS to an image and Kaleido looks like what I was wishing for.

**Comment by krizvi-mg** [comment]
Same, bumping this one. Would be very helpful.

**Comment by AtanasAtanasov** [comment]
would be helpful for me as well. Bump.

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
