### ISSUE TITLE
ENH: Support DevTools protocol scope, pyppeteer/puppeteer backend?

### ISSUE THREAD

**Issue by jonmmease** [plotly/Kaleido#28]
In principle, it should be possible to write a scope that exposes the [Chrome DevTools protocol](https://chromedevtools.github.io/devtools-protocol/).  The `headless_shell` example C++ app (https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md#usage-as-a-c_library) already does this over a local port, but it should be possible to adapt it to Kaleido's architecture where requests are sent as JSON bundles to standard-in and responses are read as JSON bundles from standard out.

For more info on Kaleido's architecture, and the benefits of this approach, see the announcement post (https://medium.com/plotly/introducing-kaleido-b03c4b7b1d81) or this repo's [README](https://github.com/plotly/Kaleido).

Would this make it possible to eventually use Kaleido as a zero-dependency backend for pyppeteer/puppeteer?  If so, this would open up a huge range of additional use-cases.

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
