### ISSUE TITLE
Determine and document minimum pip version for installation on Linux

### ISSUE THREAD

**Issue by jonmmease** [plotly/Kaleido#30]
Kaleido uses the `manylinux2014` platform tag on Linux, and old versions of pip don't understand it. We should determine the minimum pip version needed, and document that in the README.

See https://github.com/plotly/Kaleido/issues/15

**Comment by WEGFan** [comment]
It should be `pip >= 19.3` as documented [here](https://github.com/pypa/manylinux)

**Comment by jonmmease** [comment]
Awesome, thanks!

**Comment by jonmmease** [comment]
Update: linux package now uses the `manylinux1` platform tag.
