### ISSUE TITLE
Docker Alpine Image : Could not find a version that satisfies the requirement kaleido (from versions: none)

### ISSUE THREAD

**Issue by JaredOzzy** [plotly/Kaleido#34]
```
ERROR: Could not find a version that satisfies the requirement kaleido (from versions: none)
ERROR: No matching distribution found for kaleido
ERROR: Service 'django' failed to build: The command '/bin/sh -c pip install kaleido' returned a non-zero code: 1
```

my dockerfile does the following thats relevent:
```
FROM python:3.7.4-alpine
RUN pip install kaleido
RUN pip install -r requirements.txt
```
i get the same issue when i added kaleido the the requirements.txt and remove the `RUN pip install kaleido` command. 

I have also tried adding versions, i get the same issues.

Also Tried running the command ` RUN install https://github.com/plotly/Kaleido/releases/download/v0.0.3/kaleido-0.0.3-py2.py3-none-manylinux2014_x86_64.whl`
```
Step 8/13 : RUN install https://github.com/plotly/Kaleido/releases/download/v0.0.3/kaleido-0.0.3-py2.py3-none-manylinux2014_x86_64.whl
 ---> Running in 528ab1a4e2e8
BusyBox v1.30.1 (2019-06-12 17:51:55 UTC) multi-call binary.

Usage: install [-cdDsp] [-o USER] [-g GRP] [-m MODE] [-t DIR] [SOURCE]... DEST

Copy files and set attributes

	-c	Just copy (default)
	-d	Create directories
	-D	Create leading target directories
	-s	Strip symbol table
	-p	Preserve date
	-o USER	Set ownership
	-g GRP	Set group ownership
	-m MODE	Set permissions
	-t DIR	Install to DIR
ERROR: Service 'django' failed to build: The command '/bin/sh -c install https://github.com/plotly/Kaleido/releases/download/v0.0.3/kaleido-0.0.3-py2.py3-none-manylinux2014_x86_64.whl' returned a non-zero code: 1
make: *** [build] Error 1
```

all i want is to be able to save a plotly graph to a file but orca is crazy mission with docker, was hoping the recommended kaleido would be less of a mission to install and get working

**Comment by jonmmease** [comment]
Hi @JaredOzzy, the first easy thing to try is updating `pip` before installing kaleido.

```
FROM python:3.7.4-alpine
RUN pip install -U pip
RUN pip install kaleido
RUN pip install -r requirements.txt
```

If you want to try to install from a pip file directly, I think you're missing `pip` in the `RUN install https://...` command. I think you would want this to be `RUN pip install https://...`. But if the issue is an old version of pip, then this command would fail as well.

**Comment by JaredOzzy** [comment]
Will give that a shot, I was using the latest pip version too.

**Comment by jonmmease** [comment]
>  I was using the latest pip version too.

Ok, well it's worth double checking. But I did just find an interesting note at the end of the platform-compatibility-tag specification: https://packaging.python.org/specifications/platform-compatibility-tags/

> Platform tags for other *nix platforms
>
> The scheme defined in PEP 425 is not generally sufficient for public distribution of wheel files to other *nix platforms. Efforts are > currently (albeit intermittently) under way to define improved compatibility tagging schemes for AIX and for **Alpine** Linux.

I'm not familiar enough with Alpine linux to understand why it wouldn't be included in the standard linux platform tag specification, but maybe something is going on here.  Could you add the output of in your container?

```python
import platform
print(platform.machine())
print(platform.architecture())
print(platform.platform())
```

Can you install numpy alright? If so, I'm wondering which of these files pip chooses (https://pypi.org/project/numpy/#files).

**Comment by jonmmease** [comment]
Oh, Alpine supports a bunch of architectures: https://alpinelinux.org/downloads/

![Screenshot_20200816_132826](https://user-images.githubusercontent.com/15064365/90340186-5f14bc80-dfc4-11ea-9a41-6e4a6cbec051.png)

Right now, I'd only expect Kaleido to work with the `x86_64` architecture.

**Comment by JaredOzzy** [comment]
Just went through a massive mission to get numpy installed, took ages for my containers to build too. 

Here is the platform results

```
>>> import platform
>>> print(platform.machine())
x86_64
>>> print(platform.architecture())
('64bit', 'ELF')
>>> print(platform.platform())
Linux-4.19.76-linuxkit-x86_64-with
>>> 
```

**Comment by jonmmease** [comment]
Ok, thanks for that info. The reason your numpy install took so long is that pip pulled in the numpy source bundle (`numpy-1.19.1.zip`) and compiled it from source.  This means that pip rejected all of the platforms that numpy is pre-compiled for.

A little searching turned up a helpful article that matches what you're seeing: https://pythonspeed.com/articles/alpine-docker-python/

> If you look at the Debian-based build above, you’ll see it’s downloading matplotlib-3.1.2-cp38-cp38-manylinux1_x86_64.whl. This is a pre-compiled binary wheel. Alpine, in contrast, downloads the source code (matplotlib-3.1.2.tar.gz), because standard Linux wheels don’t work on Alpine Linux.
>
> Why? Most Linux distributions use the GNU version (glibc) of the standard C library that is required by pretty much every C program, including Python. But Alpine Linux uses musl, those binary wheels are compiled against glibc, and therefore Alpine disabled Linux wheel support.

FWIW, the article's conclusion is "Don’t use Alpine Linux for Python images".  Is changing the image base an option for you?

**Comment by JaredOzzy** [comment]
> Ok, thanks for that info. The reason your numpy install took so long is that pip pulled in the numpy source bundle (`numpy-1.19.1.zip`) and compiled it from source. This means that pip rejected all of the platforms that numpy is pre-compiled for.
> 
> A little searching turned up a helpful article that matches what you're seeing: https://pythonspeed.com/articles/alpine-docker-python/
> 
> > If you look at the Debian-based build above, you’ll see it’s downloading matplotlib-3.1.2-cp38-cp38-manylinux1_x86_64.whl. This is a pre-compiled binary wheel. Alpine, in contrast, downloads the source code (matplotlib-3.1.2.tar.gz), because standard Linux wheels don’t work on Alpine Linux.
> > Why? Most Linux distributions use the GNU version (glibc) of the standard C library that is required by pretty much every C program, including Python. But Alpine Linux uses musl, those binary wheels are compiled against glibc, and therefore Alpine disabled Linux wheel support.
> 
> FWIW, the article's conclusion is "Don’t use Alpine Linux for Python images". Is changing the image base an option for you?

it is an option, but damn i don't think its worth it at this moment, ill just go with matplotlib for now instead as the image is easy to save . still have to install numpy and go through all the issues though but yeah, alpine hasn't really been an issue for me at the moment.

ill try to convert it perhaps...

**Comment by jmoore87jr** [comment]
It must be an Alpine thing.

`FROM python:3` works fine.

**Comment by qqaatw** [comment]
Same problem.

**Comment by namitha109tech** [comment]
![image](https://user-images.githubusercontent.com/86408671/128675554-e341deef-1462-48bb-9152-cdacc128280c.png)

![image](https://user-images.githubusercontent.com/86408671/128675605-662c0bea-b3fe-43a8-a5c8-aa885dc3b75f.png)



I have been in the issue for 3 days , please give me a solution to do the build success

**Comment by awoodevpub** [comment]
Greetings, 

is there any update on this? I need to provide kaleido to my alpine docker image :(

**Comment by awoodevpub** [comment]
I've figured it out, just install miniconda3/miniforge within alpine dockerfile and then you can install kaleido from anaconda

Note: do not use forge as channel, I installed miniforge and just do $ RUN conda install -y python-kaleido; It's a lot of effort for just one package but until now I couldn't figure out an easier solution. Maybe an APK should be published for kaleido in order to avoid all this mess

Regards!

**Comment by ishita2326** [comment]
Hey, any solution? I'm facing a similar issue while installing dash

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson

**Comment by VictorGarritano** [comment]
Hello! Any updates on supporting Kaleido in Alpine images?

**Comment by chicco785** [comment]
how was this completed? I can't still install Kaleido :(
