### ISSUE TITLE
Manually specify executable path

### ISSUE THREAD

**Issue by jaymegordo** [plotly/Kaleido#55]
I'm trying to include kaleido in a gui app created with pyinstaller.

Most users of the app won't need to use the kaleido functionality, so I'm trying to avoid bundling the executable with the app (due to size).

I can download the latest release from the github channel and add it to a local dir on the users sysem pretty easily, but is there a way to manually specify a path to the kaleido executable?

I'm looking in `kaleido.scopes.base.py` here:

```
    @classmethod
    def executable_path(cls):
        vendored_executable_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            'executable',
            'kaleido'
        )
        if os.path.exists(vendored_executable_path):
            # The kaleido executable is vendored under kaleido/executable.
            # It was probably install as a PyPI wheel
            executable_path = vendored_executable_path
        else:
            # The kaleido executable is not vendored under kaleido/executable,
            # Probably installed using conda, where the executable is a separate package
            # and is placed on the system PATH
            executable_path = which("kaleido")
            if executable_path is None:
                path = os.environ.get("PATH", os.defpath)
                formatted_path = path.replace(os.pathsep, "\n    ")
                raise ValueError(
                    """
The kaleido executable is required by the kaleido Python library, but it was not included
in the Python package and it could not be found on the system PATH.

Searched for included kaleido executable at:
    {vendored_executable_path} 

Searched for executable 'kaleido' on the following system PATH:
    {formatted_path}\n""".format(
                        vendored_executable_path=vendored_executable_path,
                        formatted_path=formatted_path,
                    )
                )

        return executable_path
```

Is there a way to make that `shutil.which("kaleido")` command find the executable somewhere else, by adding it to the system path or something like that?

Thanks!

**Comment by jaymegordo** [comment]
Okay I kinda hacked it by importing `kaleido.scopes.base.py` before using plotly/kaleido and `write_image`
```
# path to where I manually downloaded kaleido
# (this is actually path to 'kaleido.cmd' on windows)
new_kaleido_path_win = 'C:/users/johndoe/appdata/local/my_app_name/extensions/kaleido/kaleido'
new_kaleido_path_mac = '/users/johndoe/Library/Application Supprt/my_app_name/extensions/kaleido/kaleido'

import kaleido.scopes.base as kaleido_base

if sys.platform.startswith('win'):
    # the windows version sets executable_path as a static attr at module level
    kaleido_base.executable_path = new_kaleido_path_win
elif sys.platform.startswith('mac'):
    # mac sets it as a classmethod of BaseScope
    kaleido_base.BaseScope.executable_path = new_kaleido_path_mac
```

Please let me know if there's a way to do this that may be less prone to breaking changes in the future. If not all good feel free to close the issue, and thanks for making kaleido so much nicer than orca!!

**Comment by jonmmease** [comment]
Hi @jaymegordo, in https://github.com/plotly/Kaleido/pull/46 an update was made to have Kaleido fall back to looking for an executable named `kaleido` on the `PATH` if it is not found bundled in the Python package.

Would this meet your need?

The 0.1.0a2 release on PyPI has this update (https://pypi.org/project/kaleido/0.1.0a2/) if you want to give it a try!

**Comment by jaymegordo** [comment]
@jonmmease perfect thank you thats exactly what I need!
