### ISSUE TITLE
`too long to load image` error when saving PDF

### ISSUE THREAD

**Issue by rasmushenningsson** [plotly/Kaleido#60]
When using Kaleido from PlotlyBase in Julia, I get the error message `too long to load image` error when saving to PDF.
See here for the issue in PlotlyBase.jl: https://github.com/sglyon/PlotlyBase.jl/issues/36

It seems like the error message is returned even though it actually manages to create the PDF.
Thus I suspect that there is a bug somewhere around here:
https://github.com/plotly/Kaleido/blob/7de733fe4bae03bb8b9957b3c130c621777df9bf/repos/kaleido/js/src/plotly/render.js#L179

**Comment by jonmmease** [comment]
Thanks for the report @rasmushenningsson. My guess is that we should bump up the timeout time here:

https://github.com/plotly/Kaleido/blob/7de733fe4bae03bb8b9957b3c130c621777df9bf/repos/kaleido/js/src/plotly/constants.js#L40-L41

Right now the pdf export times out after 2 seconds.  Could you try increasing that time a bit and see if that also resolves the problem?  A reference point of what time works in your case would be useful.
