### ISSUE TITLE
Support additional architectures

### ISSUE THREAD

**Issue by jonmmease** [plotly/Kaleido#7]
Right now we are building Kaleido on 64-bit MacOS, Linux, and Windows.  Folks may eventually be interested in builds for other architectures.

In addition to those above, it looks like Chromium also supports 32-bit Windows and Linux, and 32-bit ARM.

If you're interested in helping out with adding support for an additional architecture, please chime in here!

**Comment by Bibo-Joshi** [comment]
Hi. Today I tried to install kaleido on my Raspberry Pi running Ubuntu and found this issue after not succeeding.
The out put of 

```python
import platform
print(platform.machine())
print(platform.architecture())
print(platform.platform())
```

is 

```shell
aarch64
('64bit', 'ELF')
Linux-5.4.0-1015-raspi-aarch64-with-glibc2.29
```

TBH I don't have a clue of architectures, hardware etc, but if there is anything I can do, I'll be happy to help bring kaleido to raspi :)

**Comment by jonmmease** [comment]
Hi @Bibo-Joshi, thanks for reaching out and providing that info!  I'm not very familiar with arm architecture flavors, but it looks like chromium does support build targets for `arm` and `arm64`: https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/chromiumos-board-porting-guide.

![Screenshot_20200816_131142](https://user-images.githubusercontent.com/15064365/90339889-1d831200-dfc2-11ea-8a36-59ef6174c630.png)

And pip packages support `armv7l` and `aarch64` platform tags: https://packaging.python.org/specifications/platform-
compatibility-tags/

Based on the result of `platform.machine`, it looks like you would need the `arm64` chromium build and the `manylinux2014-aarch64` platform tag.

It looks like a pretty simple change in the CI configuration to build for arm, but I don't have anything set up to test on. If you're interested in trying out a test build, I think I could at least try building one on CI at some point over the next week or so.

**Comment by Bibo-Joshi** [comment]
Thanks for the quick reply!

> If you're interested in trying out a test build, I think I could at least try building one on CI at some point over the next week or so.

Yes, absolutely :)

**Comment by jonmmease** [comment]
Update: As of 0.0.3.post1, win-32 and linux-arm64 builds are available in addition to win-64, linux-64, and macos-64.

Some other architectures that could potentially be supported in the future:
 - win-arm64: https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md
 - linux-arm (32-bit I think): https://chromium.googlesource.com/chromium/src.git/+/master/docs/linux/chromium_arm.md

**Comment by jonmmease** [comment]
Closing in favor of dedicated issues for each architecture
