### ISSUE TITLE
Kaleido installation

### ISSUE THREAD

**Issue by vanshikaa2498** [plotly/Kaleido#79]
Hi!

I am trying to install kaleido on my system using 

` pip3 install -U kaleido`

but I am getting the following error:

```
Could not find a version that satisfies the requirement kaleido (from versions: )
No matching distribution found for kaleido
```
I also tried to install manually using the github release link but when I executed my file I was redirected to orca which needs an executable image for further processing.

`ValueError:
The orca executable is required to export figures as static images,
but it could not be found on the system path.`

Setup details:

> Ubuntu 14.04.6 
> Arm64 arch
> Python 3.6.9
> Plotly 4.14.3

**Comment by jonmmease** [comment]
Hi @vanastassiou.

Kaleido supports an arm linux package with platform tag `manylinux2014_aarch64.whl`. This requires `pip >= 19.3` for installation, so the first thing I'd recommend is updating pip if you have an older version.

I *think* the Arm64 ubuntu should be compatible with the `aarch64` architecture, but based on https://github.com/pypa/manylinux Ubuntu 14.04 may not be compatible with the `manylinux2014` platform tag.

As an experiment, you could try downloading the wheel file and renaming the platform tag part of the file name to `manylinux1_aarch64.whl` and see if that will install, and if it works properly.

**Comment by vanshikaa2498** [comment]
Thanks for the quick reply @jonmmease !

You are right my pip version is old. It is pip 9.0.1.
But when I am trying to upgrade it using 

`python3 -m pip install --upgrade pip`

I am getting this message:

> Requirement already up-to-date: pip in /usr/lib/python3/dist-packages

I think this might be because of my ubuntu version. Any suggestions?

**Comment by vanshikaa2498** [comment]
@jonmmease I updated my pip to pip 21.0.1 and it worked like a charm.. Thank you so much !!
