### ISSUE TITLE
Can not install on Raspberry Pi 4

### ISSUE THREAD

**Issue by Maxinger15** [plotly/Kaleido#84]
Hello,
I tried to install kaleido via sudo pip3 install kaleido but get the following error:

Could not find a version that satisfies the requirement kaleido (from versions: )
No matching distribution found for kaleido

My system:
Raspberry Pi 4
![image](https://user-images.githubusercontent.com/47686016/115045513-dd6c8a00-9ed6-11eb-9bf8-3cc36651d7f8.png)

**Comment by jonmmease** [comment]
Hi @Maxinger15,  thanks for the report. We did quite recently publish the first armv71 build, but it's not something I can test personally at the moment (@tapiralec did the work and testing on this).

One thought though is that you may need to update your version of pip. Older versions don't understand the more recent linux platform tags, in which case they refuse to install.

**Comment by Maxinger15** [comment]
Thank you for your message. I updated pip from v18.1 to v21.0.1 and now it works. 
Then i run into this error:
ValueError: Failed to start Kaleido subprocess. Error stream:

./bin/kaleido: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

and I fixed it with:
sudo apt install libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev

Now it works fine. Thank you for your help.

**Comment by jonmmease** [comment]
great! :tada:

**Comment by Lef-F** [comment]
> Thank you for your message. I updated pip from v18.1 to v21.0.1 and now it works. Then i run into this error: ValueError: Failed to start Kaleido subprocess. Error stream:
> 
> ./bin/kaleido: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
> 
> and I fixed it with: sudo apt install libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev
> 
> Now it works fine. Thank you for your help.

I ran into that error now with `kaleido` `v0.2.1.post1` on a Raspberry Pi.
Could @Maxinger15 elaborate why the installation of `libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev` is necessary to work around the `libnss3.so` issue?

I'm on `Linux 5.10.103-v7l+ armv7l GNU/Linux` and your advice fixed the issue, so really grateful for this one. 🙏
