### ISSUE TITLE
Use Semantic Versioning

### ISSUE THREAD

**Issue by FranzForstmayr** [plotly/Kaleido#89]
Current versioning scheme breaks tools which are heavily depending on semantic versioning, like poetry https://python-poetry.org/
The actual version `0.2.1`.post is not compatible with semver https://semver.org/.

Semver provides a regex check for versions here:
https://regex101.com/r/Ly7O1x/3/

It would work already if you replace the last dot with a dash, like `0.2.1-post`

**Comment by FranzForstmayr** [comment]
I just found https://www.python.org/dev/peps/pep-0440/#post-release-separators :)

**Comment by jmigual** [comment]
By the way, I found out that you can install version 0.2.1. instead of post1 (as the later only added support for ARM) by doing `poetry add kaleido==0.2.1` and it works fine.
