### ISSUE TITLE
export from R?

### ISSUE THREAD

**Issue by bigomics** [plotly/Kaleido#93]
Can we export a plotly image from R with Kaleido? How to do this?

**Comment by jonmmease** [comment]
Hi @bigomics, I'm not sure whether the R-plotly library has kaleido support. Maybe @cpsievert could chime in?

**Comment by cpsievert** [comment]
No, the R package only has support for `orca()` at the moment

**Comment by jackparmer** [comment]
I believe that @cpsievert recently updated this?

**Comment by cpsievert** [comment]
Yea, the development version now has `save_image()`, which uses `kaleido()` under the hood.

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
