### ISSUE TITLE
Export to PDF fails, but PNG and SVG work

### ISSUE THREAD

**Issue by wdecoster** [plotly/Kaleido#95]
Hi,

A user of my tool opened https://github.com/wdecoster/NanoPlot/issues/266. do you have some pointers on how to troubleshoot?
Kaleido is used here: https://github.com/wdecoster/NanoPlot/blob/master/nanoplotter/plot.py#L68
Errors are caught and logged. It turns out that exporting to PDF fails, but PNG and SVG do work...

Thanks,
Wouter

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson
